src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(length: 255)]
    private ?string $energie = null;

    #[ORM\Column]
    private ?int $place = null;

    #[ORM\Column(length: 255)]
    private ?string $transmission = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\Column]
    private ?int $kilometrage = null;

    #[ORM\Column(length: 255)]
    private ?string $couleur = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column]
    private ?int $prix_caution = null;

    #[ORM\ManyToOne(inversedBy: 'vehicule')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Agence $agence = null;

    #[ORM\OneToOne(mappedBy: 'vehicule', cascade: ['persist', 'remove'])]
    private ?Reservation $reservation = null;


    public function __construct()
    {
        $this->agences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getEnergie(): ?string
    {
        return $this->energie;
    }

    public function setEnergie(string $energie): self
    {
        $this->energie = $energie;

        return $this;
    }

    public function getPlace(): ?int
    {
        return $this->place;
    }

    public function setPlace(int $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): self
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getPrixCaution(): ?int
    {
        return $this->prix_caution;
    }

    public function setPrixCaution(int $prix_caution): self
    {
        $this->prix_caution = $prix_caution;

        return $this;
    }

    public function getAgence(): ?Agence
    {
        return $this->agence;
    }

    public function setAgence(?Agence $agence): self
    {
        $this->agence = $agence;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(Reservation $reservation): self
    {
        // set the owning side of the relation if necessary
        if ($reservation->getVehicule() !== $this) {
            $reservation->setVehicule($this);
        }

        $this->reservation = $reservation;

        return $this;
    }

}

src/Form/VehiculeType.php
<?php

namespace App\Form;

use App\Entity\Vehicule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('marque')
            ->add('modele')
            ->add('energie')
            ->add('place')
            ->add('transmission')
            ->add('categorie')
            ->add('kilometrage')
            ->add('couleur')
            ->add('prix_journalier')
            ->add('prix_caution')
            ->add('agence')
            ->add('reservation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicule::class,
        ]);
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Vehicule;
use App\Form\VehiculeType;
use App\Repository\VehiculeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/vehicule', name: 'vehicule_')]
class VehiculeController extends AbstractController
{
    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(VehiculeRepository $vehiculeRepository): Response
    {
        return $this->render('vehicule/index.html.twig', [
            'vehicules' => $vehiculeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, VehiculeRepository $vehiculeRepository): Response
    {
        $vehicule = new Vehicule();
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vehiculeRepository->save($vehicule, true);

            return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vehicule/new.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Vehicule $vehicule): Response
    {
        return $this->render('vehicule/show.html.twig', [
            'vehicule' => $vehicule,
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Vehicule $vehicule, VehiculeRepository $vehiculeRepository): Response
    {
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vehiculeRepository->save($vehicule, true);

            return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vehicule/edit.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Vehicule $vehicule, VehiculeRepository $vehiculeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicule->getId(), $request->request->get('_token'))) {
            $vehiculeRepository->remove($vehicule, true);
        }

        return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vehicule/_delete_form.html.twig
<form method="post" action="{{ path('app_vehicule_delete', {'id': vehicule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vehicule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/vehicule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vehicule{% endblock %}

{% block body %}
    <h1>Edit Vehicule</h1>

    {{ include('vehicule/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vehicule_index') }}">back to list</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}

templates/vehicule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule index{% endblock %}

{% block body %}
    <h1>Vehicule index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Marque</th>
                <th>Modele</th>
                <th>Energie</th>
                <th>Place</th>
                <th>Transmission</th>
                <th>Categorie</th>
                <th>Kilometrage</th>
                <th>Couleur</th>
                <th>Prix_journalier</th>
                <th>Prix_caution</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vehicule in vehicules %}
            <tr>
                <td>{{ vehicule.id }}</td>
                <td>{{ vehicule.marque }}</td>
                <td>{{ vehicule.modele }}</td>
                <td>{{ vehicule.energie }}</td>
                <td>{{ vehicule.place }}</td>
                <td>{{ vehicule.transmission }}</td>
                <td>{{ vehicule.categorie }}</td>
                <td>{{ vehicule.kilometrage }}</td>
                <td>{{ vehicule.couleur }}</td>
                <td>{{ vehicule.prixJournalier }}</td>
                <td>{{ vehicule.prixCaution }}</td>
                <td>
                    <a href="{{ path('app_vehicule_show', {'id': vehicule.id}) }}">show</a>
                    <a href="{{ path('app_vehicule_edit', {'id': vehicule.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_vehicule_new') }}">Create new</a>
{% endblock %}

templates/vehicule/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vehicule{% endblock %}

{% block body %}
    <h1>Create new Vehicule</h1>

    {{ include('vehicule/_form.html.twig') }}

    <a href="{{ path('app_vehicule_index') }}">back to list</a>
{% endblock %}

templates/vehicule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule{% endblock %}

{% block body %}
    <h1>Vehicule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vehicule.id }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ vehicule.marque }}</td>
            </tr>
            <tr>
                <th>Modele</th>
                <td>{{ vehicule.modele }}</td>
            </tr>
            <tr>
                <th>Energie</th>
                <td>{{ vehicule.energie }}</td>
            </tr>
            <tr>
                <th>Place</th>
                <td>{{ vehicule.place }}</td>
            </tr>
            <tr>
                <th>Transmission</th>
                <td>{{ vehicule.transmission }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ vehicule.categorie }}</td>
            </tr>
            <tr>
                <th>Kilometrage</th>
                <td>{{ vehicule.kilometrage }}</td>
            </tr>
            <tr>
                <th>Couleur</th>
                <td>{{ vehicule.couleur }}</td>
            </tr>
            <tr>
                <th>Prix_journalier</th>
                <td>{{ vehicule.prixJournalier }}</td>
            </tr>
            <tr>
                <th>Prix_caution</th>
                <td>{{ vehicule.prixCaution }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vehicule_index') }}">back to list</a>

    <a href="{{ path('app_vehicule_edit', {'id': vehicule.id}) }}">edit</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}